#https://medium.com/@caring_smitten_gerbil_914/understanding-the-events-context-in-nginx-how-it-shapes-server-performance-%EF%B8%8F-c33bf0ae4c61
#nginx configuration file, will be copied from dockerfile
worker_processes auto;

events 
{
	worker_connections 1024;
}

http 
{
	server 
	{
    	listen 443 ssl;
    	listen [::]:443 ssl;
		server_name gule-bat.42.fr;

		ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/html/; #copy content from wp here i think
		# root /var/www/html; #copy content from wp here i think
		index index.php;
		# index.html

		location / 
		{
			try_files $uri $uri/ /index.php$is_args$args;
		}

		location ~ \.php
		{
			# try_files $uri = 404;
			include fastcgi_params;
			fastcgi_pass wordpress:9000; #wordpress port
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}